title: Cleaner Blog
description: A Blog Theme by the BTC Raspberry Pi Club
email: your-email@example.com
author: btc-raspberrypiclub
baseurl: "/cleaner-blog-jekyll"
url: "https://btc-raspberrypiclub.github.io"

# Social Profiles
twitter_username:
github_username: btc-raspberrypiclub
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
